spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/employee
    username: employee
    password: 1
    driverClassName: org.postgresql.Driver
server:
  port: 8088
